/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.DTO.CampoDTO;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Admin
 */
public class DataConversion extends javax.swing.JFrame {

    /**
     * Creates new form DataConversion
     */
    public DataConversion() {
        initComponents();
        btnConcatenar.setEnabled(false);
        btnMinuscula.setEnabled(false);
        btnMayuscula.setEnabled(false);
        btnExtraerF.setEnabled(false);
        cmbIOpciones.setVisible(false);
        btnConfirmarOperacion.setVisible(false);
        DefaultComboBoxModel camposT =new DefaultComboBoxModel();

        if(FormularioETL.camposSelectOrigen.isEmpty()){
              int i = 0;
                          
                for (CampoDTO campo : MenuPrincipal.campos) {
                    
                     camposT.addElement(MenuPrincipal.campos.get(i).getColumnName()+" "+MenuPrincipal.campos.get(i).getDataType()
                             +" "+MenuPrincipal.campos.get(i).getMaxLength());
                    i++;
                }
        }else{
              int i = 0;
                          
                for (CampoDTO campo : FormularioETL.camposSelectOrigen) {
                    
                     camposT.addElement(MenuPrincipal.campos.get(i).getColumnName()+" "+MenuPrincipal.campos.get(i).getDataType()
                             +" "+MenuPrincipal.campos.get(i).getMaxLength());
                    i++;
                }
        }
        this.cmbCamposTran.setModel(camposT);

        
            
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCamposTran = new javax.swing.JComboBox<>();
        btnMinuscula = new javax.swing.JButton();
        btnMayuscula = new javax.swing.JButton();
        btnExtraerF = new javax.swing.JButton();
        btnConcatenar = new javax.swing.JButton();
        cmbIOpciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnConfirmarOperacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Transformar Datos");

        cmbCamposTran.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbCamposTran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCamposTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamposTranActionPerformed(evt);
            }
        });

        btnMinuscula.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnMinuscula.setText("Convertir a minúscula");
        btnMinuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusculaActionPerformed(evt);
            }
        });

        btnMayuscula.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnMayuscula.setText("Convertir a minúscula");
        btnMayuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayusculaActionPerformed(evt);
            }
        });

        btnExtraerF.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnExtraerF.setText("Extraer Elementos Fecha");
        btnExtraerF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerFActionPerformed(evt);
            }
        });

        btnConcatenar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConcatenar.setText("Concatenar");
        btnConcatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatenarActionPerformed(evt);
            }
        });

        cmbIOpciones.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbIOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIOpciones.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Campos");

        btnConfirmarOperacion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConfirmarOperacion.setText("Confirmar ");

        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("***");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMinuscula)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnMayuscula))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cmbCamposTran, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnExtraerF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(btnConcatenar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(cmbIOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(btnConfirmarOperacion))))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCamposTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarOperacion))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinuscula)
                    .addComponent(btnMayuscula)
                    .addComponent(btnExtraerF)
                    .addComponent(btnConcatenar))
                .addGap(32, 32, 32)
                .addComponent(btnSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExtraerFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerFActionPerformed
          cmbIOpciones.setVisible(true);
        btnConfirmarOperacion.setVisible(true);
        btnConfirmarOperacion.setText("Extraer");
    }//GEN-LAST:event_btnExtraerFActionPerformed

    private void btnMinusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinusculaActionPerformed

    private void btnMayusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayusculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMayusculaActionPerformed

    private void cmbCamposTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamposTranActionPerformed
          String TipoCampos;
           cmbIOpciones.setVisible(false);
        btnConfirmarOperacion.setVisible(false);
        if(FormularioETL.camposSelectOrigen.isEmpty()){
           
            TipoCampos = MenuPrincipal.campos.get(cmbCamposTran.getSelectedIndex()).getDataType();
            if ("VARCHAR2".equals(TipoCampos) || "CHAR".equals(TipoCampos)) {
                btnConcatenar.setEnabled(true);
                btnMinuscula.setEnabled(true);
                btnMayuscula.setEnabled(true);
                btnExtraerF.setEnabled(false);

            }else if("TIMESTAMP".equals(TipoCampos) || "DATE".equals(TipoCampos)){
                btnConcatenar.setEnabled(false);
                btnMinuscula.setEnabled(false);
                btnMayuscula.setEnabled(false);
                btnExtraerF.setEnabled(true);

             }else{
                  btnConcatenar.setEnabled(false);
                btnMinuscula.setEnabled(false);
                btnMayuscula.setEnabled(false);
                btnExtraerF.setEnabled(false);

            }
 
       }else{
                 TipoCampos = FormularioETL.camposSelectOrigen.get(cmbCamposTran.getSelectedIndex()).getDataType();
            if ("VARCHAR2".equals(TipoCampos) || "CHAR".equals(TipoCampos)) {
                btnConcatenar.setEnabled(false);
                btnMinuscula.setEnabled(false);
                btnMayuscula.setEnabled(false);
                btnExtraerF.setEnabled(false);

            }else if("TIMESTAMP".equals(TipoCampos) || "DATE".equals(TipoCampos)){
                btnConcatenar.setEnabled(false);
                btnMinuscula.setEnabled(false);
                btnMayuscula.setEnabled(false);
                btnExtraerF.setEnabled(true);

             }
       }
        
        
    }//GEN-LAST:event_cmbCamposTranActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatenarActionPerformed
         cmbIOpciones.setVisible(true);
        btnConfirmarOperacion.setVisible(true);
        btnConfirmarOperacion.setText("Concatenar Campo");
    }//GEN-LAST:event_btnConcatenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcatenar;
    private javax.swing.JButton btnConfirmarOperacion;
    private javax.swing.JButton btnExtraerF;
    private javax.swing.JButton btnMayuscula;
    private javax.swing.JButton btnMinuscula;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbCamposTran;
    private javax.swing.JComboBox<String> cmbIOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
