/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.DTO.CampoDTO;
import clases.ExtracionDatosOrigen;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormularioETL extends javax.swing.JFrame {
    
    //ESTRUCTURAR PARA OBTENER LAS TABLAS DE ORIGEN
    public static ExtracionDatosOrigen tablasPorConexion = new ExtracionDatosOrigen();
     public static ArrayList<String> tablas = new ArrayList<String>();
         public static ArrayList<CampoDTO> camposSelectOrigen = new ArrayList<CampoDTO>();

     
     public static String tablaSeleccionada;
    /**
     * Creates new form FormularioETL
     */
    public FormularioETL() {
        initComponents();
        cmbTablas.setEnabled(true);
        txaConsultaSQL.setEnabled(false);
        cmbTablas.setEnabled(false);
        btnEscogerCampos.setEnabled(false);
        
        
    }
    
   
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioETL().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrTipoExtraccion = new javax.swing.ButtonGroup();
        pnlExtracion = new javax.swing.JPanel();
        jrbTabla = new javax.swing.JRadioButton();
        jrbConsulta = new javax.swing.JRadioButton();
        cmbTablas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaConsultaSQL = new javax.swing.JTextArea();
        btnExtraerBD = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnEscogerCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlExtracion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "EXTRACCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gloucester MT Extra Condensed", 0, 18))); // NOI18N

        bgrTipoExtraccion.add(jrbTabla);
        jrbTabla.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jrbTabla.setText("Tabla:");
        jrbTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTablaActionPerformed(evt);
            }
        });

        bgrTipoExtraccion.add(jrbConsulta);
        jrbConsulta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jrbConsulta.setText("Consulta:");
        jrbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsultaActionPerformed(evt);
            }
        });

        cmbTablas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTablasActionPerformed(evt);
            }
        });

        txaConsultaSQL.setColumns(20);
        txaConsultaSQL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txaConsultaSQL.setRows(5);
        jScrollPane1.setViewportView(txaConsultaSQL);

        btnExtraerBD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExtraerBD.setText("Extraer Datos");
        btnExtraerBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerBDActionPerformed(evt);
            }
        });

        btnEscogerCampos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEscogerCampos.setText("ESCOGER CAMPOS");
        btnEscogerCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExtracionLayout = new javax.swing.GroupLayout(pnlExtracion);
        pnlExtracion.setLayout(pnlExtracionLayout);
        pnlExtracionLayout.setHorizontalGroup(
            pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtracionLayout.createSequentialGroup()
                .addGroup(pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbConsulta)
                    .addComponent(jrbTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addComponent(cmbTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnExtraerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(pnlExtracionLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnEscogerCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExtracionLayout.setVerticalGroup(
            pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTabla)
                    .addComponent(cmbTablas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jrbConsulta))
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnExtraerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlExtracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlExtracionLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnEscogerCampos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlExtracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlExtracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTablaActionPerformed
         cmbTablas.setEnabled(true);  // Habilitar cmbTablas
         txaConsultaSQL.setEnabled(false);  // Deshabilitar txaConsultaSQL
         txaConsultaSQL.setText("");
         cmbTablas.removeAllItems();
         
         try{
                this.tablas = tablasPorConexion.obtenerTablas(MenuPrincipal.ConexionOrigen.getUsername(),CredecialesConexion.conOrigen);

                // MOSTRAMOS LA LISTA DE TABLAS QUE EL SCHEMA POSEE

                 DefaultComboBoxModel modelTablas =new DefaultComboBoxModel();
            
                  int i = 0;
                      modelTablas.addElement("Selecciona una tabla");
                for (String tabla : tablas) {
                       modelTablas.addElement(tablas.get(i).toString());
                        i++;
                }
                
                this.cmbTablas.setModel(modelTablas);
        }catch  (Exception e){
            JOptionPane.showMessageDialog(this, "No se pudo establecer conexion con las tablas ." + e.getMessage());

        }
         
         
         
         
    }//GEN-LAST:event_jrbTablaActionPerformed

    private void cmbTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTablasActionPerformed
     
    }//GEN-LAST:event_cmbTablasActionPerformed

    private void jrbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsultaActionPerformed
        cmbTablas.setEnabled(false);  // Deshabilitar cmbTablas
        txaConsultaSQL.setEnabled(true);  // Habilitar txaConsultaSQL
        cmbTablas.removeAllItems();
        
    }//GEN-LAST:event_jrbConsultaActionPerformed

    private void btnExtraerBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerBDActionPerformed
        if(jrbTabla.isSelected()==true){  
            if(cmbTablas.getSelectedItem().toString()=="Selecciona una tabla"){
                JOptionPane.showMessageDialog(this, "Seleccione una tabla");
            }
            else{
               MenuPrincipal.campos = MenuPrincipal.camposPorTabla.obtenerCampos(CredecialesConexion.conOrigen, cmbTablas.getSelectedItem().toString());
               tablaSeleccionada= cmbTablas.getSelectedItem().toString();
               btnEscogerCampos.setEnabled(true);
            }
         }else if(jrbConsulta.isSelected()==true){
            try {	
                String consultaSQL =txaConsultaSQL.getText();
                MenuPrincipal.campos = MenuPrincipal.camposPorTabla.obtenerCamposConsulta(CredecialesConexion.conOrigen, consultaSQL);
                if(txaConsultaSQL.getText()==null ||txaConsultaSQL.getText().isEmpty() ){
                    JOptionPane.showMessageDialog(null, "El campo de consulta SQL está vacío. Por favor, ingresa una consulta.", "Advertencia", JOptionPane.WARNING_MESSAGE);

                }
                else{
                    if (MenuPrincipal.campos != null) {
                        JOptionPane.showMessageDialog(this, "La consulta es correcta");
                        btnEscogerCampos.setEnabled(true);    
                    } else {
                        JOptionPane.showMessageDialog(this, "La consulta no produjo resultados válidos. Intente nuevamente.");

                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al ejecutar la consulta: "+e.getMessage() );

            }
              
        }else if(jrbTabla.isSelected()==false &&jrbConsulta.isSelected()==false ){
            JOptionPane.showMessageDialog(this, "Eligar una opcion para extraer los datos, ya sea por tabla o consulta");

        }
              
          
    }//GEN-LAST:event_btnExtraerBDActionPerformed

    private void btnEscogerCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerCamposActionPerformed
        FrmEscogerCampos frmEscogerC = new FrmEscogerCampos();      
            frmEscogerC.setLocationRelativeTo(this);  // Centra la ventana con respecto a la ventana principal
            frmEscogerC.setVisible(true);  // Mostrar la ventana
    }//GEN-LAST:event_btnEscogerCamposActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrTipoExtraccion;
    private javax.swing.JButton btnEscogerCampos;
    private javax.swing.JButton btnExtraerBD;
    private javax.swing.JComboBox<String> cmbTablas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JRadioButton jrbConsulta;
    public static javax.swing.JRadioButton jrbTabla;
    private javax.swing.JPanel pnlExtracion;
    private javax.swing.JTextArea txaConsultaSQL;
    // End of variables declaration//GEN-END:variables
}
