/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import clases.DTO.CampoDTO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmEscogerCampos extends javax.swing.JFrame {
          DefaultListModel<String> listModel = new DefaultListModel<>();

    public FrmEscogerCampos() {
        initComponents();
        jlsCamposSeleccionados.setEnabled(false);
        jlsCamposSeleccionados.setBackground(Color.WHITE);
        btnGuardarCampos.setEnabled(false);
        if (FormularioETL.jrbConsulta.isSelected()) {
            lbltabla.setText("CONSULTA");
        }else if(FormularioETL.jrbTabla.isSelected()){
            lbltabla.setText("TABLA "+FormularioETL.tablaSeleccionada);
        }

                 DefaultComboBoxModel modelcampos =new DefaultComboBoxModel();
            
                  int i = 0;
                          
                for (CampoDTO campo : MenuPrincipal.campos) {
                    
                     modelcampos.addElement(MenuPrincipal.campos.get(i).getColumnName()+" "+MenuPrincipal.campos.get(i).getDataType()
                             +" "+MenuPrincipal.campos.get(i).getMaxLength());
                    i++;
                }
                
                this.cmbCamposTablaOrigen.setModel(modelcampos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCamposTablaOrigen = new javax.swing.JComboBox<>();
        btnAgregarC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsCamposSeleccionados = new javax.swing.JList<>();
        lbltabla = new javax.swing.JLabel();
        btnGuardarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("CAMPOS DE LA ");

        cmbCamposTablaOrigen.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbCamposTablaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCamposTablaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamposTablaOrigenActionPerformed(evt);
            }
        });

        btnAgregarC.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAgregarC.setText("Agregar Campos");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("CAMPOS SELECCIONADOS");

        jlsCamposSeleccionados.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jlsCamposSeleccionados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jlsCamposSeleccionados);

        lbltabla.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbltabla.setText("TABLA");

        btnGuardarCampos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnGuardarCampos.setText("Guardar Y salir");
        btnGuardarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltabla))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(cmbCamposTablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarC))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbltabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCamposTablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAgregarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGuardarCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCamposTablaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamposTablaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCamposTablaOrigenActionPerformed

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        
        try {
            // Obtener el elemento seleccionado del JComboBox
            String selectedItem = (String) cmbCamposTablaOrigen.getSelectedItem();
            int indexCampo = cmbCamposTablaOrigen.getSelectedIndex();
            
            
                      // Construir el formato del elemento que se agregará al listModel

              String elemento = MenuPrincipal.campos.get(indexCampo).getColumnName() + " " +
               MenuPrincipal.campos.get(indexCampo).getDataType() + " " +
                MenuPrincipal.campos.get(indexCampo).getMaxLength();
            boolean existeLista = false;
            for (int i = 0; i < listModel.getSize(); i++) {
                if (listModel.getElementAt(i).equals(elemento)) {
                    existeLista = true;
                    break;
                }
            }

            if (selectedItem != null) {
                if(!existeLista){
                    /*listModel.addElement(FormularioETL.camposSelectOrigen.get(indexCampo).getColumnName()+" "+FormularioETL.camposSelectOrigen.get(indexCampo).getDataType()
                             +" "+FormularioETL.camposSelectOrigen.get(indexCampo).getMaxLength());*/
                    
              
                    listModel.addElement(elemento); // Agregar al modelo de la lista

                     jlsCamposSeleccionados.setModel(listModel);
                     FormularioETL.camposSelectOrigen.add(MenuPrincipal.campos.get(indexCampo));
                     btnGuardarCampos.setEnabled(true);

                }else{
                    JOptionPane.showMessageDialog(this, "Ya selecciono ese campo");
  
                }      
                
               

           
                
            }   
            
            
        }catch(Exception e) {
                
           JOptionPane.showMessageDialog(this, "Succedio un error inesperado"+ e.getMessage());

        }
       
            
            
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void btnGuardarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCamposActionPerformed
        dispose();
    }//GEN-LAST:event_btnGuardarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarC;
    public static javax.swing.JButton btnGuardarCampos;
    private javax.swing.JComboBox<String> cmbCamposTablaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlsCamposSeleccionados;
    private javax.swing.JLabel lbltabla;
    // End of variables declaration//GEN-END:variables
}
